config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root to: "store#index"
  resources :products
  resources :products do
    get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A Livraria Online</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all',
                            'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 
                            'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="main">
      <%= image_tag 'logo.svg', alt: 'A Livraria' %>
      <h1><%= @page_title %></h1>
    </header>
    <section class="content">
      <nav class="side_nav">
        <% if @cart %>
          <div id="cart" class="carts">
            <%= render_if @cart && @cart.line_items.any?, @cart %>
          </div>
        <% end %>
        <ul>
          <li><a href= <%= root_path %> >Home</a></li>
          <li><a href="/questions">Perguntas</a></li>
          <li><a href="/news">Notícias</a></li>
          <li><a href="/contact">Contato</a></li>
        </ul>
        <% if current_user %>
          <nav class="logged_in_nav">
            <ul>
              <li><%= link_to 'Pedidos', orders_path %></li>
              <li><%= link_to 'Livros', products_path %></li>
              <li><%= link_to 'Usuários', users_path %></li>
              <li><%= button_to 'Logout', destroy_user_session_path, method: :delete   %></li>
            </ul>
          </nav>
        <% end %>
      </nav>
      <main class='<%= controller.controller_name %>'>
        <%= yield %>
      </main>
    </section>
  </body>
</html>